create table patrimonio.localizacao (id  bigserial not null, created timestamp not null, updated timestamp, codigo varchar(255), descricao varchar(255), recno varchar(255), tipo_localizacao varchar(255), primary key (id));
create table patrimonio.marca (id  bigserial not null, created timestamp not null, updated timestamp, nome varchar(255) not null, primary key (id));
create table patrimonio.modelo (id  bigserial not null, created timestamp not null, updated timestamp, nome varchar(255) not null, marca_id int8 not null, primary key (id));
alter table patrimonio.patrimonio add column capacidade varchar(255);
alter table patrimonio.patrimonio add column codigo_base varchar(255) not null;
alter table patrimonio.patrimonio add column complemento varchar(255);
alter table patrimonio.patrimonio add column departamento varchar(255);
alter table patrimonio.patrimonio add column descricao varchar(255);
alter table patrimonio.patrimonio add column encontrado boolean not null;
alter table patrimonio.patrimonio add column nome varchar(255) not null;
alter table patrimonio.patrimonio add column numero_serie varchar(255);
alter table patrimonio.patrimonio add column observacao varchar(255);
alter table patrimonio.patrimonio add column localizacao_id int8 not null;
alter table patrimonio.patrimonio add column modelo_id int8;
alter table patrimonio.marca drop constraint if exists UK_marca_nome;
alter table patrimonio.marca add constraint UK_marca_nome unique (nome);
alter table patrimonio.modelo drop constraint if exists UKjumbtwiadnnoxnyktgdkaw2aj;
alter table patrimonio.modelo add constraint UKjumbtwiadnnoxnyktgdkaw2aj unique (nome, marca_id);
alter table patrimonio.modelo drop constraint if exists UK_modelo_nome;
alter table patrimonio.modelo add constraint UK_modelo_nome unique (nome);
alter table patrimonio.patrimonio drop constraint if exists UK3fvhxukh57sp62iqmd5guyot4;
alter table patrimonio.patrimonio add constraint UK3fvhxukh57sp62iqmd5guyot4 unique (numero, nome, codigo_base);
create table patrimonio_audit.localizacao_audit (id int8 not null, revision int8 not null, revision_type int2, codigo varchar(255), descricao varchar(255), recno varchar(255), tipo_localizacao varchar(255), primary key (id, revision));
create table patrimonio_audit.marca_audit (id int8 not null, revision int8 not null, revision_type int2, nome varchar(255), primary key (id, revision));
create table patrimonio_audit.modelo_audit (id int8 not null, revision int8 not null, revision_type int2, nome varchar(255), marca_id int8, primary key (id, revision));
alter table patrimonio_audit.patrimonio_audit add column capacidade varchar(255);
alter table patrimonio_audit.patrimonio_audit add column codigo_base varchar(255);
alter table patrimonio_audit.patrimonio_audit add column complemento varchar(255);
alter table patrimonio_audit.patrimonio_audit add column departamento varchar(255);
alter table patrimonio_audit.patrimonio_audit add column descricao varchar(255);
alter table patrimonio_audit.patrimonio_audit add column encontrado boolean;
alter table patrimonio_audit.patrimonio_audit add column nome varchar(255);
alter table patrimonio_audit.patrimonio_audit add column numero_serie varchar(255);
alter table patrimonio_audit.patrimonio_audit add column observacao varchar(255);
alter table patrimonio_audit.patrimonio_audit add column localizacao_id int8;
alter table patrimonio_audit.patrimonio_audit add column modelo_id int8;
alter table patrimonio.modelo add constraint FK_modelo_marca_id foreign key (marca_id) references patrimonio.marca;
alter table patrimonio.patrimonio add constraint FK_patrimonio_localizacao_id foreign key (localizacao_id) references patrimonio.localizacao;
alter table patrimonio.patrimonio add constraint FK_patrimonio_modelo_id foreign key (modelo_id) references patrimonio.modelo;
alter table patrimonio_audit.localizacao_audit add constraint FK_localizacao_audit_revision foreign key (revision) references public.revision;
alter table patrimonio_audit.marca_audit add constraint FK_marca_audit_revision foreign key (revision) references public.revision;
alter table patrimonio_audit.modelo_audit add constraint FK_modelo_audit_revision foreign key (revision) references public.revision;