create table patrimonio.centro_custo_inventario (id  bigserial not null, created timestamp not null, updated timestamp, centro_custo_id int8 not null, inventario_id int8 not null, primary key (id));
create table patrimonio.executor (id  bigserial not null, created timestamp not null, updated timestamp, centro_custo_inventario_id int8 not null, usuario_id int8 not null, primary key (id));
create table patrimonio.inventario (id  bigserial not null, created timestamp not null, updated timestamp, data_inicio date not null, data_termino date not null, nome varchar(255) not null, primary key (id));
create table patrimonio.patrimonio (id  bigserial not null, created timestamp not null, updated timestamp, numero varchar(255) not null, centro_custo_inventario_id int8 not null, primary key (id));
alter table patrimonio.centro_custo_inventario drop constraint if exists UK44jk7bgq8n59ygtvn4fcyry2q;
alter table patrimonio.centro_custo_inventario add constraint UK44jk7bgq8n59ygtvn4fcyry2q unique (inventario_id, centro_custo_id);
alter table patrimonio.executor drop constraint if exists UKeuyle06hjq9jc75rxskbh7bt2;
alter table patrimonio.executor add constraint UKeuyle06hjq9jc75rxskbh7bt2 unique (centro_custo_inventario_id, usuario_id);
alter table patrimonio.inventario drop constraint if exists UK_inventario_nome;
alter table patrimonio.inventario add constraint UK_inventario_nome unique (nome);
alter table patrimonio.patrimonio drop constraint if exists UKplh1os8ktgygi7je4mriogjnf;
alter table patrimonio.patrimonio add constraint UKplh1os8ktgygi7je4mriogjnf unique (numero, centro_custo_inventario_id);
alter table patrimonio.patrimonio drop constraint if exists UK_patrimonio_numero;
alter table patrimonio.patrimonio add constraint UK_patrimonio_numero unique (numero);
create table patrimonio_audit.centro_custo_inventario_audit (id int8 not null, revision int8 not null, revision_type int2, centro_custo_id int8, inventario_id int8, primary key (id, revision));
create table patrimonio_audit.executor_audit (id int8 not null, revision int8 not null, revision_type int2, centro_custo_inventario_id int8, usuario_id int8, primary key (id, revision));
create table patrimonio_audit.inventario_audit (id int8 not null, revision int8 not null, revision_type int2, data_inicio date, data_termino date, nome varchar(255), primary key (id, revision));
create table patrimonio_audit.patrimonio_audit (id int8 not null, revision int8 not null, revision_type int2, numero varchar(255), centro_custo_inventario_id int8, primary key (id, revision));
create table pessoal.centro_custo (id  bigserial not null, created timestamp not null, updated timestamp, codigo varchar(255) not null, descricao varchar(500) not null, gestor_id int8 not null, primary key (id));
alter table pessoal.centro_custo drop constraint if exists UK_centro_custo_codigo;
alter table pessoal.centro_custo add constraint UK_centro_custo_codigo unique (codigo);
create table pessoal_audit.pessoal_audit (id int8 not null, revision int8 not null, revision_type int2, codigo varchar(255), descricao varchar(255), gestor_id int8, primary key (id, revision));
alter table patrimonio.centro_custo_inventario add constraint FK_centro_custo_inventario_centro_custo_id foreign key (centro_custo_id) references pessoal.centro_custo;
alter table patrimonio.centro_custo_inventario add constraint FK_centro_custo_inventario_inventario_id foreign key (inventario_id) references patrimonio.inventario;
alter table patrimonio.executor add constraint FK_executor_centro_custo_inventario_id foreign key (centro_custo_inventario_id) references patrimonio.centro_custo_inventario;
alter table patrimonio.executor add constraint FK_executor_usuario_id foreign key (usuario_id) references configuracao.usuario;
alter table patrimonio.patrimonio add constraint FK_patrimonio_centro_custo_inventario_id foreign key (centro_custo_inventario_id) references patrimonio.centro_custo_inventario;
alter table patrimonio_audit.centro_custo_inventario_audit add constraint FK_centro_custo_inventario_audit_revision foreign key (revision) references public.revision;
alter table patrimonio_audit.executor_audit add constraint FK_executor_audit_revision foreign key (revision) references public.revision;
alter table patrimonio_audit.inventario_audit add constraint FK_inventario_audit_revision foreign key (revision) references public.revision;
alter table patrimonio_audit.patrimonio_audit add constraint FK_patrimonio_audit_revision foreign key (revision) references public.revision;
alter table pessoal.centro_custo add constraint FK_centro_custo_gestor_id foreign key (gestor_id) references configuracao.usuario;
alter table pessoal_audit.pessoal_audit add constraint FK_pessoal_audit_revision foreign key (revision) references public.revision;
