#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:
  jmx.enabled: false

  #DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://ptipgsqlt.fpti.pti.org.br:5432/inventario_t
    username: sa_inventario_t
    password: aLuXLsefzU2NYSUa

  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: br.org.pti.api.functional.inventario.infrastructure.hibernate.constraint.ConstraintsImplicitNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: br.org.pti.api.functional.inventario.infrastructure.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.default_schema: public
      org.hibernate.envers.audit_table_suffix: _audited
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow

  #STATIC RESOURCES
  resources.static-locations: classpath:/META-INF/resources/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**

  #THYMELEAF
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/META-INF/resources/
    suffix: .html

  #FLYWAY
  flyway:
    check-location: false
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix:
    baseline-version: 0

#WEB CONTAINER
server:
  port: 8080
  compression.enabled: true
  servlet:
    context-path:
    session.persistent: true
    session.timeout: 999999999

#LDAP
ldap:
  url: ldap://dc01.fpti.pti.org.br
  domain: fpti.pti.org.br
  base: DC=FPTI,DC=PTI,DC=ORG,DC=BR
  baseDn: OU=Colaboradores,DC=FPTI,DC=PTI,DC=ORG,DC=BR
  searchBase: OU=Colaboradores
  username: CN=bindinventariot,OU=Aplicacoes,DC=fpti,DC=pti,DC=org,DC=br
  password: ZtVMhjcLw6rFLL38
  userPrincipalPath: sAMAccountName=

# configuracoes do actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ['health', 'info', 'flyway' , 'logfile']
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    flyway:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/${spring.application.name}/${spring.application.name}.log

# configuracoes de logging
logging.level:
  root: INFO
  org.hibernate: INFO
  org.springframework: INFO
  org.springframework.web: INFO
  org.springframework.security: INFO
  org.springframework.web.client: INFO
  org.springframework.context.support: INFO
  org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

# configs de logging
logging:
  file: /var/log/${spring.application.name}/${spring.application.name}.log

# informacoes do sistema
info:
  app:
    name: ${spring.application.name}
    module: ${spring.application.name}
    version: @project.version@-@project.build-number@
    environment: @active.profile@
    url: ${spring.application.name}.pti.org.br

oauth:
  endpoints:
    centros-custo: http://localhost:8082/api/centroscusto/
    colaboradores: http://localhost:8082/api/funcionarios/
    patrimonios: http://localhost:8082/api/patrimonios/
    localizacoes: http://localhost:8082/api/localizacoes/
  token: http://localhost:8081/oauth/token
  clientId: patrimonio
  clientSecret: O8p7ndZmf3DQY0Q2
