spring:
  datasource:
    url: jdbc:postgresql://ptipgsqldmz.fpti.pti.org.br:5432/portaldecompras
    username: sa_portaldecompras
    password: A76Pq4BnZBRxPweaGGYV6D
    hikari.maximum-pool-size: 10

  jpa:
    hibernate.ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  mail:
    host: info-fpti.fpti.pti.org.br
    port: 587
    username: portaldecompras@ptisb01dmz.fpti.pti.org.br
    password: srk6G3evkD4FvvrMQVbhpF
    properties:
      mail.transport.protocol: smtp
      mail.smtp.starttls.enable: true
      mail.smtps.debug: false
      mail.smtp.debug: false
      mail.debug: false

ldap:
  url: ldap://dc01.fpti.pti.org.br
  username: CN=bindportaldecompras,OU=Aplicacoes,DC=fpti,DC=pti,DC=org,DC=br
  password: MguMxdQ6WXDhGu88

oauth:
  endpoints:
    fornecedores: https://integrador.pti.org.br/compras/fornecedores/
    bancos: https://integrador.pti.org.br/financeiro/bancos/
    cidades: https://integrador.pti.org.br/compras/municipios/
  token: https://integrador.pti.org.br/autorizador/oauth/token
  clientId: portalcompras
  username: portalcompras
  password: portalcompras

info:
  url: portaldecompras.pti.org.br
