#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:
  application.name: books
  jmx.enabled: false

  #DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://127.0.0.1:5432/books
    username: books
    password: books

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: br.com.emanuelvictor.books.application.configuration.ConstraintsImplicitNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: br.com.emanuelvictor.books.infrastructure.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.default_schema: public
      org.hibernate.envers.audit_table_suffix: _audited
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type

  #STATIC RESOURCES
  resources.static-locations: classpath:/META-INF/resources/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**

  #THYMELEAF
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/META-INF/resources/
    suffix: .html

  #FLYWAY
  flyway:
    check-location: false
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: v
    baseline-version: 0

#WEB CONTAINER
server:
  compression.enabled: true
  servlet:
    session.persistent: true
    session.timeout: 999999999

# configuracoes do actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ['health', 'info', 'flyway' , 'logfile']
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    flyway:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/${spring.application.name}/${spring.application.name}.log

# configuracoes de logging
logging.level:
  root: INFO
  org.hibernate: INFO
  org.springframework: INFO
  org.springframework.web: INFO
  org.springframework.security: INFO
  org.springframework.context.support: INFO
  org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

# configs de logging
logging:
  file: /var/log/${spring.application.name}/${spring.application.name}.log

# informacoes do sistema
info:
  app:
    name: vigilanciaintegrada
    module: ${spring.application.name}
    version: @project.version@
    environment: @active.profile@
