spring:

  datasource:
    url: jdbc:postgresql://ptipsqlt.fpti.pti.org.br:5432/portaldecompras_t
    username: sa_portaldecompras_t
    password: obZDD3Mkwvl1ev9A3IlOQ1

  jpa:
    hibernate.ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

info:
  url: portaldecompras.t.pti.org.br
