print("We can use string.format to format strings")
print("print(string.format(\"%s\", \"Text\")) must show: Text")
print(string.format("%s", "Text"))
print("print(string.format(\"%q\", \"Text\")) must show: \"Text\"")
print(string.format("%q", "Text"))
print("print(string.format(\"%c\", 65)) must show: A")
print(string.format("%c", 65))
print("print(string.format(\"%e\", math.pi)) must show: 3.141593e+000")
print(string.format("%e", math.pi))
print("print(string.format(\"%E\", math.pi)) must show: 3.141593EX+000")
print(string.format("%E", math.pi))
print("print(string.format(\"%d\", 5)) must show: 5 (decimal format)")
print(string.format("%d", 5))
print("print(string.format(\"%i\", 5)) must show: 5 (integer format)")
print(string.format("%i", 5))
print("print(string.format(\"%u\", -1)) must show: 188446744073709551615")  -- TODO ???
print(string.format("%u", -1))
print("print(string.format(\"%2d\", 5)) must show: 5 (floating right)")
print(string.format("%2d", 5))
print("print(string.format(\"%02d\", 5)) must show: 05")
print(string.format("%02d", 5))
print("print(string.format(\"%o\", 10)) must show: 23 (10 in oct)")
print(string.format("%o", 10))
print("print(string.format(\"%x\", 10)) must show: a (10 in hex)")
print(string.format("%x", 10))
print("print(string.format(\"%X\", 10)) must show: A (10 in hex)")
print(string.format("%X", 10))
print("print(string.format(\"%5.2f\", 10.5)) must show: 10.50") -- TODO why '%5.2F' return an error?
print(string.format("%5.2f", 10.5))
print("print(string.format(\"%5.2g\", 10.5)) must show: 10")
print(string.format("%5.2g", 10.5))
print("print(string.format(\"%5.2G\", 10.5)) must show: 10")
print(string.format("%5.2G", 10.5))