#Configuração destinada ao ambiente de produção
#GENERAL
spring:

  #DATA SOURCE
  datasource:
    url: jdbc:postgresql://ptipgsqldmz.fpti.pti.org.br:5432/inventario
    username: sa_inventario
    password: XZNSUx9Xxa2Z7eDg
    hikari.maximum-pool-size: 3

  #JPA
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  #STATIC RESOURCES
  resources.chain:
    cache: false

  #FLYWAY
  flyway:
    enabled: true

#LDAP
ldap:
  url: ldap://dc01.fpti.pti.org.br
  username: CN=bindinventario,OU=Aplicacoes,DC=fpti,DC=pti,DC=org,DC=br
  password: MgJTYesTfAFX4sMt

oauth:
  endpoints:
    centros-custo: https://integrador.pti.org.br/contabilidade/centroscusto/
    colaboradores: https://integrador.pti.org.br/recursoshumanos/funcionarios/
    patrimonios: https://integrador.pti.org.br/ativofixo/patrimonios/
    localizacoes: https://integrador.pti.org.br/ativofixo/localizacoes/
  token: https://integrador.pti.org.br/autorizador/oauth/token
  clientId: patrimonio
  username: patrimonio
  password: 6U6cdYdl

info:
  url: inventario.pti.org.br
