--
-- PostgreSQL database dump
--

-- Dumped from database version 10.13
-- Dumped by pg_dump version 10.13

-- Started on 2020-08-14 22:31:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 1 (class 3079 OID 12924)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner:
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2892 (class 0 OID 0)
-- Dependencies: 1
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner:
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 199 (class 1259 OID 41095)
-- Name: group; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.group (
                                     id bigint NOT NULL,
                                     created_on timestamp without time zone NOT NULL,
                                     updated_on timestamp without time zone,
                                     name character varying(50) NOT NULL
);


ALTER TABLE public.group OWNER TO "access-manager";

--
-- TOC entry 196 (class 1259 OID 41083)
-- Name: group_audit; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.group_audit (
                                           id bigint NOT NULL,
                                           revision bigint NOT NULL,
                                           revision_type smallint,
                                           name character varying(50)
);


ALTER TABLE public.group_audit OWNER TO "access-manager";

--
-- TOC entry 198 (class 1259 OID 41093)
-- Name: group_id_seq; Type: SEQUENCE; Schema: public; Owner: access-manager
--

ALTER TABLE public.group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- TOC entry 201 (class 1259 OID 41102)
-- Name: group_permission; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.group_permission (
                                                id bigint NOT NULL,
                                                created_on timestamp without time zone NOT NULL,
                                                updated_on timestamp without time zone,
                                                group_permission_id bigint NOT NULL,
                                                permission_id bigint NOT NULL
);


ALTER TABLE public.group_permission OWNER TO "access-manager";

--
-- TOC entry 197 (class 1259 OID 41088)
-- Name: group_permission_audit; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.group_permission_audit (
                                                      id bigint NOT NULL,
                                                      revision bigint NOT NULL,
                                                      revision_type smallint,
                                                      group_permission_id bigint,
                                                      permission_id bigint
);


ALTER TABLE public.group_permission_audit OWNER TO "access-manager";

--
-- TOC entry 200 (class 1259 OID 41100)
-- Name: group_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: access-manager
--

ALTER TABLE public.group_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_permission_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- TOC entry 203 (class 1259 OID 41109)
-- Name: application; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.application (
                                    id bigint NOT NULL,
                                    created_on timestamp without time zone NOT NULL,
                                    updated_on timestamp without time zone,
                                    access_token_validity_seconds integer NOT NULL,
                                    authorized_grant_types character varying(255),
                                    client_id character varying(45) NOT NULL,
                                    client_secret character varying(90) NOT NULL,
                                    revoke_token_url character varying(500),
                                    refresh_token_validity_seconds integer NOT NULL,
                                    registered_redirect_uri character varying(255),
                                    resource_ids character varying(255),
                                    scoped boolean NOT NULL,
                                    secret_required boolean NOT NULL,
                                    group_id bigint NOT NULL
);


ALTER TABLE public.application OWNER TO "access-manager";

--
-- TOC entry 204 (class 1259 OID 41117)
-- Name: application_audit; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.application_audit (
                                          id bigint NOT NULL,
                                          revision bigint NOT NULL,
                                          revision_type smallint,
                                          access_token_validity_seconds integer,
                                          authorized_grant_types character varying(255),
                                          client_id character varying(45),
                                          client_secret character varying(90),
                                          revoke_token_url character varying(500),
                                          refresh_token_validity_seconds integer,
                                          registered_redirect_uri character varying(255),
                                          resource_ids character varying(255),
                                          scoped boolean,
                                          secret_required boolean,
                                          group_id bigint
);


ALTER TABLE public.application_audit OWNER TO "access-manager";

--
-- TOC entry 202 (class 1259 OID 41107)
-- Name: application_id_seq; Type: SEQUENCE; Schema: public; Owner: access-manager
--

ALTER TABLE public.application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- TOC entry 206 (class 1259 OID 41127)
-- Name: permission; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.permission (
                                   id bigint NOT NULL,
                                   created_on timestamp without time zone NOT NULL,
                                   updated_on timestamp without time zone,
                                   authority character varying(255) NOT NULL,
                                   name character varying(255) NOT NULL,
                                   description character varying(255),
                                   upper_permission_id bigint
);


ALTER TABLE public.permission OWNER TO "access-manager";

--
-- TOC entry 207 (class 1259 OID 41132)
-- Name: permission_audit; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.permission_audit (
                                         id bigint NOT NULL,
                                         revision bigint NOT NULL,
                                         revision_type smallint,
                                         authority character varying(255),
                                         name character varying(255),
                                         description character varying(255),
                                         upper_permission_id bigint
);


ALTER TABLE public.permission_audit OWNER TO "access-manager";

--
-- TOC entry 205 (class 1259 OID 41125)
-- Name: permission_id_seq; Type: SEQUENCE; Schema: public; Owner: access-manager
--

ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- TOC entry 209 (class 1259 OID 41139)
-- Name: revisions; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.revisions (
                                  id bigint NOT NULL,
                                  created_by character varying(45) NOT NULL,
                                  created_on timestamp without time zone NOT NULL
);


ALTER TABLE public.revisions OWNER TO "access-manager";

--
-- TOC entry 208 (class 1259 OID 41137)
-- Name: revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: access-manager
--

ALTER TABLE public.revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revisions_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- TOC entry 211 (class 1259 OID 41146)
-- Name: user; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public."user" (
                               id bigint NOT NULL,
                               created_on timestamp without time zone NOT NULL,
                               updated_on timestamp without time zone,
                               enabled boolean NOT NULL,
                               locked boolean NOT NULL,
                               name character varying(250) NOT NULL,
                               password character varying(100) NOT NULL,
                               username character varying(150) NOT NULL,
                               group_id bigint NOT NULL
);


ALTER TABLE public."user" OWNER TO "access-manager";

--
-- TOC entry 212 (class 1259 OID 41154)
-- Name: user_audit; Type: TABLE; Schema: public; Owner: access-manager
--

CREATE TABLE public.user_audit (
                                   id bigint NOT NULL,
                                   revision bigint NOT NULL,
                                   revision_type smallint,
                                   enabled boolean,
                                   locked boolean,
                                   name character varying(250),
                                   password character varying(100),
                                   username character varying(150),
                                   group_id bigint
);


ALTER TABLE public.user_audit OWNER TO "access-manager";

--
-- TOC entry 210 (class 1259 OID 41144)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: access-manager
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- TOC entry 2725 (class 2606 OID 41087)
-- Name: group_audit group_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_audit
    ADD CONSTRAINT group_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2727 (class 2606 OID 41092)
-- Name: group_permission_audit group_permission_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_permission_audit
    ADD CONSTRAINT group_permission_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2733 (class 2606 OID 41106)
-- Name: group_permission group_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_permission
    ADD CONSTRAINT group_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 2729 (class 2606 OID 41099)
-- Name: group group_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group
    ADD CONSTRAINT group_pkey PRIMARY KEY (id);


--
-- TOC entry 2739 (class 2606 OID 41124)
-- Name: application_audit application_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.application_audit
    ADD CONSTRAINT application_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2737 (class 2606 OID 41116)
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);


--
-- TOC entry 2745 (class 2606 OID 41136)
-- Name: permission_audit permission_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.permission_audit
    ADD CONSTRAINT permission_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2741 (class 2606 OID 41131)
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);


--
-- TOC entry 2747 (class 2606 OID 41143)
-- Name: revisions revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.revisions
    ADD CONSTRAINT revisions_pkey PRIMARY KEY (id);


--
-- TOC entry 2731 (class 2606 OID 41163)
-- Name: group uk_2rpgfvxump55l2ycp3bjhgi8j; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group
    ADD CONSTRAINT uk_2rpgfvxump55l2ycp3bjhgi8j UNIQUE (name);


--
-- TOC entry 2735 (class 2606 OID 41165)
-- Name: group_permission uk_group_permission; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_permission
    ADD CONSTRAINT uk_group_permission UNIQUE (group_permission_id, permission_id);


--
-- TOC entry 2743 (class 2606 OID 41167)
-- Name: permission uk_atogak43scua5hr2pnnaevywq; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT uk_atogak43scua5hr2pnnaevywq UNIQUE (authority);


--
-- TOC entry 2749 (class 2606 OID 41169)
-- Name: user uk_sb8bbouer5wak8vyiiy4pf2bx; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT uk_sb8bbouer5wak8vyiiy4pf2bx UNIQUE (username);


--
-- TOC entry 2753 (class 2606 OID 41161)
-- Name: user_audit user_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.user_audit
    ADD CONSTRAINT user_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2751 (class 2606 OID 41153)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 2754 (class 2606 OID 41170)
-- Name: group_audit fk_group_audit_revisions; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_audit
    ADD CONSTRAINT fk_group_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2756 (class 2606 OID 41180)
-- Name: group_permission fk_group_permission_group; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_permission
    ADD CONSTRAINT fk_group_permission_group FOREIGN KEY (group_permission_id) REFERENCES public.group(id);


--
-- TOC entry 2755 (class 2606 OID 41175)
-- Name: group_permission_audit fk_group_permission_audit_revisions; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_permission_audit
    ADD CONSTRAINT fk_group_permission_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2757 (class 2606 OID 41185)
-- Name: group_permission fk_group_permission_permission; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.group_permission
    ADD CONSTRAINT fk_group_permission_permission FOREIGN KEY (permission_id) REFERENCES public.permission(id);


--
-- TOC entry 2758 (class 2606 OID 41190)
-- Name: application fk_application_group; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fk_application_group FOREIGN KEY (group_id) REFERENCES public.group(id);


--
-- TOC entry 2759 (class 2606 OID 41195)
-- Name: application_audit fk_application_audit_revisions; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.application_audit
    ADD CONSTRAINT fk_application_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2761 (class 2606 OID 41205)
-- Name: permission_audit fk_permission_audit_revisions; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.permission_audit
    ADD CONSTRAINT fk_permission_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2760 (class 2606 OID 41200)
-- Name: permission fk_permission_permission; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fk_permission_permission FOREIGN KEY (upper_permission_id) REFERENCES public.permission(id);


--
-- TOC entry 2762 (class 2606 OID 41210)
-- Name: user fk_user_group; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_group FOREIGN KEY (group_id) REFERENCES public.group(id);


--
-- TOC entry 2763 (class 2606 OID 41215)
-- Name: user_audit fk_user_audit_revisions; Type: FK CONSTRAINT; Schema: public; Owner: access-manager
--

ALTER TABLE ONLY public.user_audit
    ADD CONSTRAINT fk_user_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


-- Completed on 2020-08-14 22:31:25

--
-- PostgreSQL database dump complete
--

