spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

info:
  version: @project.version@

management:
  endpoint:
    logfile:
      external-file: /${user.home}/${spring.application.name}.log

logging:
  file:
    name: /${user.home}/${spring.application.name}.log
server:
  port: 8081
